from typing import Optional

import torch
from torch import nn, Tensor
from torchaudio.functional import resample
from connear import CoNNearPeriphery


class CoSDRLoss(nn.Module):
    """Cochlear-domain SDR loss based on auditory representations generated by
    the CoNNear auditory periphery model.

    The input signals are first resampled to 20 kHz and transformed into
    cochlear representations using the selected stages of the auditory
    processing pipeline. The loss is then computed as a negative SDR (nSDR)
    in the auditory domain.

    Optionally, the auditory representations can be:
        - normalized by their RMS energy prior to loss computation;
        - projected onto the target representation to obtain a
          scale-invariant criterion, similarly to SI-SDR.

    The loss supports variable-length signals within a batch. When signals
    are zero-padded to match a common length, temporal masks are internally
    computed so that padded regions are excluded from the loss computation.

    Args:
        n_cf (int): Number of cochlear frequency channels used
            to compute the auditory representation. Supported values are
            21 and 201. Defaults to `201`.
        use_ihc (bool): If `True`, includes the inner hair cell
            (IHC) stage in the auditory processing pipeline.
            Defaults to `False`.
        use_anf (bool): If `True`, includes the auditory nerve
            fiber (ANF) stages in the auditory processing pipeline.
            Requires `use_ihc=True`. Defaults to `False`.
        norm (bool): If `True`, normalizes auditory representations 
            by their RMS energy before computing the loss.
            Defaults to `True`.
        scale_invariant (bool): If `True`, applies a projection
            of the target auditory representation onto the estimated one to
            obtain a scale-invariant criterion analogous to SI-SDR.
            Defaults to `True`.
    """
    def __init__(self,
                 n_cf: int=201,
                 use_ihc: bool=False,
                 use_anf: bool=False,
                 norm: bool=True,
                 scale_invariant: bool=True) -> None:
        super(CoSDRLoss, self).__init__()
        self.loss_fn = neg_nsdr
        self.norm = norm
        self.scale_invariant = scale_invariant
        
        self.connear = CoNNearPeriphery(n_cf=n_cf, use_ihc=use_ihc, use_anf=use_anf)
        self.connear.eval()
        for p in self.connear.parameters():
            p.requires_grad = False
            
    @staticmethod
    def _compute_scaling(r_target: Tensor, r_estim: Tensor, mask: Tensor, eps: float=1e-8) -> Tensor:
        """Compute the optimal scale factor for scale-invariant projection.

        This method computes a per-example scaling coefficient that projects
        the estimated auditory representation onto the target representation,
        similarly to the projection step used in SI-SDR. The scaling is computed
        only over valid time-frequency regions specified by `mask`.

        The scaling factor is defined as:

            alpha = <r_estim, r_target> / ||r_target||²

        where `<., .>` denotes the inner product over the masked
        time-frequency dimensions.

        Args:
            r_target (Tensor): Target auditory representations with shape
                `(B, C, F, T)`.
            r_estim (Tensor): Estimated auditory representations with shape
                `(B, C, F, T)`.
            mask (Tensor): Binary mask indicating valid regions of the
                representations. Must be broadcastable to `r_target`.
                Valid entries should be `1.0` and padded regions
                should be `0.0`.
            eps (float): Small numerical constant added to the denominator for
                numerical stability. Defaults to `1e-8`.

        Returns:
            Tensor: Scaling coefficients with shape `(B, 1, 1, 1)`,
            containing one scale factor per batch item.
        """
        r_target_m = r_target * mask
        r_estim_m = r_estim * mask
        dot = (r_estim_m * r_target_m).sum(dim=(-1, -2), keepdim=True)
        norm = (r_target_m * r_target_m).sum(dim=(-1, -2), keepdim=True).detach()
        alpha = dot / (norm + eps)
        return alpha

    @staticmethod
    def _preprocess(in_sig: Tensor, orig_sr: int=16000, target_sr: int=20000) -> Tensor:
        batch_size = in_sig.shape[0]
        out_sig = resample(in_sig, orig_freq=orig_sr, new_freq=target_sr)
        out_sig = out_sig.view(batch_size, 1, -1)
        return out_sig
    
    @staticmethod
    def _make_time_mask(r: Tensor, lengths_frames: Tensor) -> Tensor:
        """Create a time mask for batched CoNNear outputs.

        Args:
            r (Tensor): Batched CoNNear outputs with shape `(B, C=1, F, T)`.
            lengths_frames (Tensor): Number of valid time frames for each
                batch item, with shape `(B,)`.

        Returns:
            Tensor: Time mask with shape `(B, 1, 1, T)`, where valid frames are
                `1.0` and padded frames are `0.0`.
        """
        batch_size, _, _, time_frames = r.shape
        idx = torch.arange(time_frames, device=r.device).unsqueeze(0)  # (1, T)
        mask = (idx < lengths_frames.unsqueeze(1)).float()    # (B, T)
        return mask.view(batch_size, 1, 1, time_frames)
    
    def forward(self, s_estim: Tensor, s_target: Tensor, lengths: Optional[Tensor]=None, orig_sr: int=16000) -> Tensor:
        """Compute the loss between estimated and target signals.

        Args:
            s_estim (Tensor): Estimated signals with shape `(B, T)`.
            s_target (Tensor): Target signals with shape `(B, T)`.
            lengths (Tensor, optional): Valid lengths for each signal in samples. If `None`,
                all time frames are treated as valid. Defaults to `None`.
            orig_sr (int): Original sampling rate of the input signals. Defaults to `16000`.

        Returns:
            Tensor: Scalar loss value averaged over the batch.
        """
        # Preprocessing: resample to 20 kHz and reshape to match expected shape
        target_sr = 20000
        s_target = self._preprocess(s_target, orig_sr=orig_sr, target_sr=target_sr)        
        s_estim = self._preprocess(s_estim, orig_sr=orig_sr, target_sr=target_sr)
        # Lengths converted to the new sample rate
        if lengths is not None:
            lengths_resampled = torch.round(lengths.float() * target_sr / orig_sr).long()
        else:
            lengths_resampled = torch.full(size=(s_target.shape[0],),
                                           fill_value=s_target.shape[-1],
                                           device=s_target.device,
                                           dtype=torch.long)    # assume no mask is needed
          
        # Compute auditory representations
        r_target = self.connear(s_target)
        r_estim = self.connear(s_estim)
    
        # dur_r/dur_s ratio to convert signal length to auditory length (should be =1)
        dur_s = s_target.shape[-1]
        dur_r = r_target.shape[-1]
        ratio = dur_r / dur_s
        len_r = torch.clamp((lengths_resampled.float() * ratio).round().long(), max=dur_r)
        
        # Compute temporal mask
        mask = self._make_time_mask(r_target, len_r)    # (B, 1, 1, len_r)

        # Compute projection for scale invariance
        if self.scale_invariant:
            alpha = self._compute_scaling(r_target, r_estim, mask)
            r_target = alpha * r_target
        # Normalize auditory representations by RMS values, computed from valid frames only
        if self.norm:
            n_valid = mask.sum(dim=3, keepdim=True).clamp(min=1)
            rms_target = torch.sqrt((r_target ** 2 * mask).sum(dim=3, keepdim=True) / n_valid + 1e-20)
            rms_estim = torch.sqrt((r_estim ** 2 * mask).sum(dim=3, keepdim=True) / n_valid + 1e-20)
            r_target = r_target / rms_target
            r_estim = r_estim / rms_estim
        return self.loss_fn(r_estim, r_target, mask)


def neg_nsdr(r_estim: Tensor, r_target: Tensor, mask: Optional[Tensor]=None, eps: float=1e-20) -> Tensor:
    """Compute the negative signal-to-distortion ratio (nSDR).

    The SDR is computed independently for each batch item as:
        nSDR = -10 * log10(||r_target||² / ||r_estim - r_target||²)
    where the energy terms are computed only over valid time-frequency
    regions specified by `mask`.

    Args:
        r_estim (Tensor): Estimated auditory representations with shape
            `(B, C, F, T)`, where:
            - `B` is the batch size,
            - `C` is the channel dimension,
            - `F` is the number of cochlear frequency channels,
            - `T` is the number of time frames.
        r_target (Tensor): Target auditory representations with shape
            `(B, C, F, T)`.
        mask (Tensor, optional): Binary mask indicating valid regions of the
            representations. Must be broadcastable to `r_target`.
            Valid entries should be `1.0` and padded/ignored regions
            should be `0.0`. If `None`, all elements are treated as
            valid. Defaults to `None`.
        eps (float): Small numerical constant added to the denominator and
            logarithm argument for numerical stability. Defaults to `1e-20`.

    Returns:
        Tensor: Scalar tensor containing the batch-averaged negative SDR
        value.
    """
    # If no mask is provided, assume all time frames are valid
    if mask is None:
        mask = torch.ones_like(r_target)

    diff = (r_estim - r_target) * mask
    # Sum over (C=1, F, T) -> a single scalar per batch item
    num = (r_target.pow(2) * mask).sum(dim=(1, 2, 3))
    den = diff.pow(2).sum(dim=(1, 2, 3)) + eps 
    nsdr = -10 * torch.log10((num/den) + eps)
    return nsdr.mean()
